apiVersion: v2
appVersion: v1.1.1
description: A Helm chart for Kubernetes to deploy telegraf-operator
home: https://github.com/influxdata/telegraf-operator
keywords:
- telegraf
- telegraf-operator
- sidecar
- operator
- injector
- mutatingwebhook
- influxdata
- influxdb
kubeVersion: '>= 1.13.0-r0'
maintainers:
- email: giacomo@influxdata.com
  name: gitirabassi
- email: rawkode@influxdata.com
  name: rawkode
name: telegraf-operator
type: application
version: 1.1.5
